# Generated by Django 6.0.3 on 2026-06-01 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('active_group', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('A+B', 'Group A and B'), ('B+A', 'Group B and A')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('group', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B')], max_length=1)),
                ('current_status', models.CharField(choices=[('ON', 'Electricity ON'), ('OFF', 'Electricity OFF'), ('UNCERTAIN', 'Uncertain')], default='UNCERTAIN', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TownshipStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('township_status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('UNCERTAIN', 'UNCERTAIN')], max_length=10)),
                ('thumb_up_count', models.PositiveIntegerField(default=0)),
                ('thumb_down_count', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('last_processed_report_id', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powertracker.township')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_rate', models.FloatField(default=100.0)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('favorite_townships', models.ManyToManyField(blank=True, to='powertracker.township')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('township_status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('UNCERTAIN', 'UNCERTAIN')], max_length=10)),
                ('vote', models.CharField(choices=[('UP', 'Thumb Up'), ('DOWN', 'Thumb Down')], max_length=4)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powertracker.township')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
