# Generated by Django 6.0.3 on 2026-06-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powertracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='township',
            name='name_mm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='township',
            name='name_zh',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
