# Generated by Django 6.0.3 on 2026-06-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powertracker', '0002_township_name_mm_township_name_zh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='active_group',
            field=models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('All', 'Group A and B')], max_length=3),
        ),
    ]
