# Generated by Django 6.0.3 on 2026-06-04 13:38

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_favorites(apps, schema_editor):
    UserProfile = apps.get_model("powertracker", "UserProfile")
    FavoriteTownship = apps.get_model("powertracker", "FavoriteTownship")
    OldFavoriteTownship = UserProfile.favorite_townships.through

    positions = {}

    for old_favorite in OldFavoriteTownship.objects.order_by("userprofile_id", "id"):
        user_profile_id = old_favorite.userprofile_id
        positions[user_profile_id] = positions.get(user_profile_id, 0) + 1

        FavoriteTownship.objects.get_or_create(
            user_profile_id=user_profile_id,
            township_id=old_favorite.township_id,
            defaults={"position": positions[user_profile_id]},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('powertracker', '0003_alter_schedule_active_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTownship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powertracker.township')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powertracker.userprofile')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'unique_together': {('user_profile', 'township')},
            },
        ),
        migrations.RunPython(copy_existing_favorites, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_townships',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_townships',
            field=models.ManyToManyField(blank=True, through='powertracker.FavoriteTownship', to='powertracker.township'),
        ),
    ]
