# Generated by Django 6.0.3 on 2026-06-09 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powertracker', '0007_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='powertracke_categor_1c0ac2_idx',
            old_name='powertracke_categor_91ce50_idx',
        ),
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='powertracke_created_00774b_idx',
            old_name='powertracke_created_7c306d_idx',
        ),
        migrations.RenameIndex(
            model_name='userreport',
            new_name='powertracke_window__762d7f_idx',
            old_name='powertracke_window__c8b893_idx',
        ),
        migrations.RenameIndex(
            model_name='userreport',
            new_name='powertracke_townshi_c6a0fc_idx',
            old_name='powertracke_townsh_7e51f7_idx',
        ),
        migrations.AddField(
            model_name='schedulenotification',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powertracker.schedule'),
        ),
        migrations.AddField(
            model_name='schedulenotification',
            name='township',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powertracker.township'),
        ),
        migrations.AddField(
            model_name='schedulenotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpushsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='schedulenotification',
            index=models.Index(fields=['user', 'sent_at'], name='powertracke_user_id_d915f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedulenotification',
            constraint=models.UniqueConstraint(fields=('user', 'township', 'schedule'), name='unique_user_township_schedule_notification'),
        ),
        migrations.AddIndex(
            model_name='userpushsubscription',
            index=models.Index(fields=['user', 'is_active'], name='powertracke_user_id_2c857b_idx'),
        ),
    ]
