# Generated by Django 6.0.3 on 2026-06-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powertracker', '0008_schedulenotification_userpushsubscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='correct_rate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='report_count',
        ),
    ]
